### PR TITLE
Pt

### PR DESCRIPTION
**Pull request by josepaulolima**
Translation of Sprint 03: folder 04-social-network.
Translation of first chapter (00-rwd).
Some images need to be translated.

### CODE REVIEW

**Comment by rafaelbcerri** [comment]
@josepaulolima your `pt` branch seems to not be updated, could you updated it using the Laboratoria/curricula-js as source and them apply your commit?

**Comment by rafaelbcerri** [comment]
@JulianaAmoasei can you start reviewing the translating? It is only the last commit.

**Comment by rafaelbcerri** [comment]
@ivandevp can you close this PR? We are going to use the [PR - 663](https://github.com/Laboratoria/curricula-js/pull/663) from now on.

**Comment by ivandevp** [comment]
Ok @rafaelbcerri. Thanks for you review.

**Pull request closed without merging**
