### PR TITLE
Sprint04

### PR DESCRIPTION
**Pull request by josepaulolima**
Unity 01 and 02 (Sprint 04).

### CODE REVIEW

**Comment by josepaulolima** [comment]
Greetings, Rafael.

If you could wait one more day before review, I would apreciate. Some of
the issues I have already fixed in my final revision.



Em qua, 15 de ago de 2018 às 17:21, Rafael Cerri <notifications@github.com>
escreveu:

**Comment by josepaulolima** [comment]
Olá, @rafaelbcerri .
Já finalizei minhas pendências.
Estou à disposição se houver necessidade de corrigir algo.

**Comment by rafaelbcerri** [comment]
@josepaulolima Obrigado!! 🎉

**Comment by rafaelbcerri** [comment]
@ivandevp Do you think you could merge it today, you do not need to deploy in staging, just merge will be enough for now?

**Pull request merged**
