### PR TITLE
Grammar and spelling revision

### PR DESCRIPTION
**Pull request by josepaulolima**
Grammar and spelling revision requested by Regina.

### CODE REVIEW

**Comment by ivandevp** [comment]
Thanks @josepaulolima! Before merging your PR, you need solve the conflicts shown above, can you do it, please?

**Comment by josepaulolima** [comment]
Hi, @ivandevp .
I'm not sure if I did something wrong, but GitHub says I don't have permission to resolve the conflicts.

**Comment by ivandevp** [comment]
@josepaulolima you will have to solve them locally, and then committing your changes and pushing them to your branch.

**Comment by rafaelbcerri** [comment]
@ivandevp you can close this PR and use [PR #676](https://github.com/Laboratoria/curricula-js/pull/676) instead.

**Pull request closed without merging**
